apiVersion: v1
kind: Service
metadata:
  name: crossplane-demo
  labels:
    app: crossplane-demo
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  selector:
    app: crossplane-demo
---