url: 192.168.64.26.nip.io
simpleApp:
- name: simple-app-prd
  namespace: simple-app-prd
  production: "yes"
  server: https://kubernetes.default.svc
- name: simple-app-dev
  namespace: simple-app-dev
  production: "no"
  server: https://kubernetes.default.svc
# - name: simple-app-feature
#   namespace: simple-app-feature
#   production: "no"
#   server: https://kubernetes.default.svc