simpleApp:
- name: simple-app-prd
  values: values-production.yaml
  namespace: simple-app-prd
  production: "yes"
- name: simple-app-dev
  values: values-development.yaml
  namespace: simple-app-dev
  production: "no"
# - name: simple-app-feature
#   values: values-feature.yaml
#   namespace: simple-app-feature
#   production: "no"