apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd
spec:
  destination:
    namespace: simple-app-prd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: resources/app-of-apps
    repoURL: https://github.com/GijsvanDulmen/sample-gitops-argocd
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true