apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-app
  namespace: argocd
spec:
  destination:
    namespace: simple-app
    server: https://kubernetes.default.svc
  project: default
  source:
    path: resources/simple-app
    repoURL: https://github.com/GijsvanDulmen/sample-gitops-argocd
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: false