{{- $root := . -}}
{{- range $app := .Values.simpleApp }}
apiVersion: v1
kind: Namespace
metadata:
    name: {{ $app.namespace | quote }}
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: "project-{{ $app.name }}"
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Simple App project
  sourceRepos:
  - '*'
  destinations:
  - namespace: {{ $app.namespace | quote }}
    server: https://kubernetes.default.svc
  clusterResourceWhitelist: []
  # none!
  namespaceResourceBlacklist:
  - group: ''
    kind: ResourceQuota
  - group: ''
    kind: LimitRange
  - group: ''
    kind: NetworkPolicy
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $app.name | quote }}
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: "project-{{ $app.name }}"
  destination:
    namespace: {{ $app.namespace | quote }}
    server: https://kubernetes.default.svc
  project: default
  source:
    path: resources/simple-app
    repoURL: https://github.com/GijsvanDulmen/sample-gitops-argocd
    targetRevision: HEAD
    helm:
      values: |
        url: "{{ $app.name }}.{{ $root.Values.url }}"
  syncPolicy:
    {{ if eq $app.production "yes" }}
    automated: {}
    {{ else }}
    automated:
      prune: true
      selfHeal: true
    {{ end }}
---
{{ end }}