{{- range $app := .Values.simpleApp }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $app.name | quote }}
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ $app.namespace | quote }}
    server: https://kubernetes.default.svc
  project: default
  source:
    path: resources/simple-app
    repoURL: https://github.com/GijsvanDulmen/sample-gitops-argocd
    targetRevision: HEAD
    helm:
      valueFiles:
      - {{ $app.values | quote }}
  syncPolicy:
    {{ if eq $app.production "yes" }}
    automated: {}
    {{ else }}
    automated:
      prune: true
      selfHeal: true
    {{ end }}
    syncOptions:
    - CreateNamespace=true
---
{{ end }}