{{- $root := . -}}
{{- range $app := .Values.simpleApp }}
apiVersion: v1
kind: Namespace
metadata:
    name: {{ $app.namespace | quote }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $app.name | quote }}
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app: "simple-app"
spec:
  destination:
    namespace: {{ $app.namespace | quote }}
    server: {{ $app.server | quote }}
  project: default
  source:
    path: resources/simple-app
    repoURL: https://github.com/GijsvanDulmen/sample-gitops-argocd
    targetRevision: HEAD
    helm:
      values: |
        url: "{{ $app.name }}.{{ $root.Values.url }}"
  syncPolicy:
    {{ if eq $app.production "yes" }}
    automated: {}
    {{ else }}
    automated:
      prune: true
      selfHeal: true
    {{ end }}
---
{{ end }}