apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-app
  labels:
    app: simple-app
spec:
  selector:
    matchLabels:
      app: simple-app
  replicas: 1
  template:
    metadata:
      labels:
        app: simple-app
    spec:
      containers:
      - name: echoserver
        image: {  .Values.image | quote }}
        imagePullPolicy: Always
        env:
          - name: SHOW_HEADERS
            value: "false"
          - name: APP_VERSION
            value: {{ .Values.version | quote }}
        resources:
          requests:
            cpu: "10m"
            memory: "101Mi"
          limits:
            cpu: "100m"
            memory: "120Mi"
        ports:
          - containerPort: 8080

        # Probes
        livenessProbe:
          httpGet:
            path: /live
            port: 8080
          initialDelaySeconds: 2
          periodSeconds: 600
          timeoutSeconds: 5
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 2
      terminationGracePeriodSeconds: 3
---