apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    link.argocd.argoproj.io/external-link: "http://{{ .Values.url }}"
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: simple-app
          servicePort: http
    host: {{ .Values.url | quote }}
---