name: Helm validation

on:
  pull_request:
    branches:
      - main

# replace with https://github.com/helm/chart-testing-action
jobs:
  helm-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        # see: https://github.com/helm/chart-testing/issues/186
        fetch-depth: "0"

    - name: Set up Helm
      uses: azure/setup-helm@v1
      with:
        version: v3.4.0

    - uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Set up chart-testing
      uses: helm/chart-testing-action@v2.0.1

    - name: Run chart-testing (list-changed)
      id: list-changed
      run: |
        changed=$(ct list-changed --remote origin --target-branch main --chart-dirs resources/simple-app)
        if [[ -n "$changed" ]]; then
          echo "::set-output name=changed::true"
        fi

    - name: List current dir
      run: pwd

    - name: List current dir s
      run: ls -ltr

    - name: Run chart-testing (lint)
      run: ct lint --all --chart-dirs resources/simple-app

    # heavy stuff - please disable :-)
    - name: Create kind cluster
      uses: helm/kind-action@v1.0.0
      if: steps.list-changed.outputs.changed == 'true'

    - name: Run chart-testing (install)
      run: ct install --all --chart-dirs resources/simple-app